version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - MONGO_URI=mongodb://mongodb:27017/personalfinance
      - JWT_SECRET=your_development_secret
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
